version: '1'

services:
  coordinator:
    depends_on:
      - hive-metastore
      - localstack
    image: phaoghost/ph-presto:latest
    container_name: coordinator
    hostname: coordinator
    volumes:
      - ./data/coordinator:/root/shared
    restart: always
    healthcheck:
      test: /etc/init.d/presto status | grep -q 'Running as'
      interval: 5m
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080
    environment:
      HIVE_METASTORE_HOST: hive-metastore
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY_ID: ${AWS_SECRET_ACCESS_KEY_ID}
      HIVE_METASTORE_PORT: 9083
      HIVE_S3_HOST: localstack
      HIVE_S3_PORT: 4566
      
  
  hive-metastore:
    depends_on:
      - postgres
      - localstack
      - s3_setup
    image: naushadh/hive-metastore
    hostname: hive-metastore
    environment:
      DATABASE_DB: postgres
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      S3_ENDPOINT_URL: http://localstack:4566
      S3_BUCKET: ${HIVE_METASTORE_S3_BUCKET}
      S3_PREFIX: ""
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY_ID}
    env_file:
      - env/postgres.env
    
  localstack:
    image: localstack/localstack
    hostname: localstack
    domainname: localstack
    ports:
    - 4566:4566

  s3_setup:
    image: localstack/localstack
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: ["aws", "--endpoint-url", "http://localstack:4566", "s3api", "create-bucket", "--bucket", "${HIVE_METASTORE_S3_BUCKET}"]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_ID}
      HIVE_METASTORE_S3_BUCKET: ${HIVE_METASTORE_S3_BUCKET}

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


